<?php
/** Validate deterministic Docs Agent completion and drift semantics. */

declare( strict_types=1 );

require_once dirname( __DIR__ ) . '/scripts/validate-docs-agent-completion.php';

$assert = static function ( bool $condition, string $message ): void { if ( ! $condition ) { throw new RuntimeException( $message ); } };
$run = static function ( string $command, string $cwd ): void { exec( 'cd ' . escapeshellarg( $cwd ) . ' && ' . $command . ' 2>&1', $output, $code ); if ( 0 !== $code ) { throw new RuntimeException( implode( "\n", $output ) ); } };
$workspace = static function () use ( $run ): string {
	$path = sys_get_temp_dir() . '/docs-agent-contract-' . bin2hex( random_bytes( 6 ) );
	mkdir( $path . '/docs', 0700, true );
	file_put_contents( $path . '/README.md', "# Project\n\nExisting project documentation.\n" );
	file_put_contents( $path . '/docs/guide.md', "# Guide\n\nExisting guide.\n" );
	$run( 'git init -q && git config user.name test && git config user.email test@example.com && git add . && git commit -qm baseline', $path );
	return $path;
};
$options = static function ( string $workspace, array $overrides = array() ): array {
	return array_merge( array( 'workspace' => $workspace, 'lane' => 'technical', 'run_kind' => 'maintenance', 'writable_paths' => 'README.md,docs/**', 'bootstrap_contract' => array(), 'source_delta' => array( array( 'id' => 'service-contract', 'source_refs' => array( 'src/service.php:10-40' ), 'requires_documentation_change' => false ) ) ), $overrides );
};
$expect_failure = static function ( string $code, callable $callback ) use ( $assert ): void {
	try { $callback(); } catch ( Docs_Agent_Contract_Failure $error ) { $assert( $code === $error->diagnostic_code, "Expected {$code}; got {$error->diagnostic_code}" ); return; }
	throw new RuntimeException( "Expected {$code}." );
};

$workspaces = array();
try {
	// Changed and no-change outcomes are observations of Git, not final model prose.
	$changed = $workspace();
	$workspaces[] = $changed;
	file_put_contents( $changed . '/docs/guide.md', "# Guide\n\nUpdated source-grounded service contract.\n" );
	$report = docs_agent_build_completion_report( $options( $changed ) );
	$assert( 'changes' === $report['outcome'] && array( 'docs/guide.md' ) === $report['changed_paths'], 'Changed outcome must come from Git.' );
	$assert( array( 'src/service.php:10-40' ) === $report['source']['refs'] && 'bounded_delta' === $report['source']['basis'], 'Source facts must come from caller records.' );

	$clean = $workspace();
	$workspaces[] = $clean;
	$no_change = docs_agent_build_completion_report( $options( $clean ) );
	$assert( 'no_changes' === $no_change['outcome'] && array() === $no_change['changed_paths'], 'No-change outcome must come from a clean Git workspace.' );
	// These represent arbitrary, malformed, and absent model final prose. The builder never reads them.
	mkdir( $clean . '/.codebox', 0700, true );
	foreach ( array( 'Normal final prose.', '<DOCS_AGENT_COMPLETION_REPORT>{not json}</DOCS_AGENT_COMPLETION_REPORT>', '' ) as $prose ) {
		file_put_contents( $clean . '/.codebox/model-final-prose.txt', $prose );
		$with_prose = docs_agent_build_completion_report( $options( $clean ) );
		$assert( 'no_changes' === $with_prose['outcome'], 'Model prose must not affect completion.' );
		unlink( $clean . '/.codebox/model-final-prose.txt' );
	}

	$validator = dirname( __DIR__ ) . '/scripts/validate-docs-agent-completion.php';
	$source_delta = base64_encode( (string) json_encode( $options( $clean )['source_delta'], JSON_THROW_ON_ERROR ) );
	$run( 'php ' . escapeshellarg( $validator ) . ' --workspace ' . escapeshellarg( $clean ) . ' --lane technical --run-kind maintenance --writable-paths ' . escapeshellarg( 'README.md,docs/**' ) . ' --source-delta-b64 ' . escapeshellarg( $source_delta ) . ' --artifact-path docs-agent-completion-report.json', $clean );
	$artifact = $clean . '/.codebox/agent-task-artifacts/docs-agent-completion-report.json';
	$assert( docs_agent_canonical_report_json( $no_change ) === file_get_contents( $artifact ), 'The command must stage canonical host-generated bytes.' );
	$expect_failure( 'ARTIFACT_PATH_INVALID', static fn() => docs_agent_write_report_artifact( $no_change, $clean, '../completion.json' ) );

	$scope = $workspace();
	$workspaces[] = $scope;
	file_put_contents( $scope . '/docs/guide.md', "# Changed\n" );
	$expect_failure( 'WRITABLE_SCOPE_VIOLATION', static fn() => docs_agent_build_completion_report( $options( $scope, array( 'writable_paths' => 'README.md' ) ) ) );

	$drift = $workspace();
	$workspaces[] = $drift;
	$expect_failure( 'KNOWN_DRIFT_NO_CHANGE', static fn() => docs_agent_build_completion_report( $options( $drift, array( 'source_delta' => array( array( 'id' => 'service-contract', 'source_refs' => array( 'src/service.php:10-40' ), 'requires_documentation_change' => true ) ) ) ) ) );
	file_put_contents( $drift . '/src.php', "<?php\n" );
	$expect_failure( 'KNOWN_DRIFT_NO_CHANGE', static fn() => docs_agent_build_completion_report( $options( $drift, array( 'writable_paths' => 'README.md,docs/**,src.php', 'source_delta' => array( array( 'id' => 'service-contract', 'source_refs' => array( 'src/service.php:10-40' ), 'requires_documentation_change' => true ) ) ) ) ) );

	$bootstrap = $workspace();
	$workspaces[] = $bootstrap;
	file_put_contents( $bootstrap . '/README.md', "# Project\n\n[Architecture](docs/architecture.md) and [Setup](docs/setup.md) provide the source-grounded project documentation.\n" );
	file_put_contents( $bootstrap . '/docs/architecture.md', '# Architecture' . str_repeat( "\n\nSource-grounded architecture guidance.", 12 ) );
	file_put_contents( $bootstrap . '/docs/setup.md', '# Setup' . str_repeat( "\n\nSource-grounded setup guidance.", 12 ) );
	$bootstrap_contract = array( 'required_paths' => array( 'README.md', 'docs/architecture.md', 'docs/setup.md' ), 'required_globs' => array( array( 'pattern' => 'docs/**/*.md', 'min' => 2 ) ), 'entry_points' => array( array( 'path' => 'README.md', 'must_link_to' => array( 'docs/architecture.md', 'docs/setup.md' ) ) ), 'forbidden_phrases' => array() );
	$bootstrap_report = docs_agent_build_completion_report( $options( $bootstrap, array( 'run_kind' => 'bootstrap', 'source_delta' => array(), 'bootstrap_contract' => $bootstrap_contract ) ) );
	$assert( true === $bootstrap_report['bootstrap']['criteria_satisfied'] && 'passed' === $bootstrap_report['checks']['bootstrap'], 'Bootstrap result must come from filesystem checks.' );

	$thin = $workspace();
	$workspaces[] = $thin;
	file_put_contents( $thin . '/README.md', "# Project\n\n[Guide](docs/guide.md)\n" );
	file_put_contents( $thin . '/docs/guide.md', "# Tiny\n" );
	$expect_failure( 'BOOTSTRAP_REQUIRED_PATH', static fn() => docs_agent_build_completion_report( $options( $thin, array( 'run_kind' => 'bootstrap', 'source_delta' => array(), 'bootstrap_contract' => array( 'required_paths' => array( 'docs/guide.md' ), 'required_globs' => array(), 'entry_points' => array(), 'forbidden_phrases' => array() ) ) ) ) );

	$assert( array( 'publish' => true, 'pr_required' => true ) === docs_agent_publication_expectation( 'changes', 'bootstrap', false ), 'Bootstrap publication must remain deterministic.' );
} finally {
	foreach ( $workspaces as $path ) { $run( 'rm -rf ' . escapeshellarg( $path ), '/' ); }
}

fwrite( STDOUT, "Docs Agent completion contract validation passed.\n" );
